spring.application.name=DisasterRecoveryBackupSystem

# SERVER CONFIG

server.port=8080

# DATABASE CONFIG

spring.datasource.url=jdbc:mysql://localhost:3306/drb_system
spring.datasource.username=root
spring.datasource.password=root9099

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / HIBERNATE
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# FILE UPLOAD SIZE
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB


# BACKUP CONFIG

backup.location=C:/backups/

backup.db.name=drb_system
backup.db.username=root
backup.db.password=root9099

backup.files.location=C:/storage/


# LOGGING
logging.level.root=INFO

logging.level.com.dr.backup=DEBUG

logging.file.name=logs/backup-system.log


# SCHEDULER CONFIG

backup.scheduler.cron=0 0/30 * * * *


# RETRY CONFIG
backup.retry.max-attempts=3
backup.retry.delay=3000


# COMPRESSION
backup.compression.enabled=true


# ENCRYPTION
backup.encryption.enabled=false


# RETENTION POLICY
backup.retention.days=7
